### ISSUE TITLE
Json int64_t Support ?

### ISSUE THREAD

**Issue by BestITUserEUW** [getml/reflect-cpp#101]
Hey,

I have a struct that i want to write and read which contains a timestamp in milliseconds of type int64_t. After parse i get:
`
"timestamp":-2125153807
`
Which is integer overflow.
Is it possible to support int64_t ?

P.S. I can't use rfl::Timestamp, timestamp has to be sent as number.

**Comment by liuzicheng1987** [comment]
@BestITUserEUW , you seem to have found a solution to this.

If you have, feel free to open a PR.

**Comment by liuzicheng1987** [comment]
A fix would basically involve minor edits in these two files:

https://github.com/getml/reflect-cpp/blob/main/include/rfl/json/Reader.hpp

https://github.com/getml/reflect-cpp/blob/main/include/rfl/json/Writer.hpp

**Comment by BestITUserEUW** [comment]
There is already a fix from #92 works now. I used v0.10.0 i'll just use main branch until it get's into a new release.

**Comment by liuzicheng1987** [comment]
Yes, of course...I forgot that that was after v0.10.0. I'll do the formal release for v0.11.0 soon.
