### ISSUE TITLE
"Field name not found" even with a default value

### ISSUE THREAD

**Issue by pupbrained** [getml/reflect-cpp#122]
I'm trying to use reflect-cpp to serialize and deserialize my configuration values, but I want to give every value a default so the program can still run without a configuration (or an incomplete one). I have the configuration split into structs:

```cpp
using Location = std::variant<std::string, Coords>;

struct General {
  std::string name = getenv("USER");
};

struct NowPlaying {
  std::optional<bool> enabled = false;
};

struct Weather {
  Location    location;
  std::string api_key;
  std::string units;

  fn getWeatherInfo() const -> WeatherOutput;
};

struct Config {
  General    general     = General();
  NowPlaying now_playing = NowPlaying();
  Weather    weather     = Weather();

  static fn getInstance() -> const Config&;
};
```

I've been testing with the General part of the config. Even though I'm supplying defaults it still complains that the fields aren't found. Is there something I'm missing or is this intended behavior? I'm not sure what else to try.

**Comment by liuzicheng1987** [comment]
@pupbrained , it doesn’t quite work that way. You need to use std::optional:

https://github.com/getml/reflect-cpp/blob/main/docs/optional_fields.md

Then, you can retrieve the values using something like config.general.value_or(General())

**Comment by pupbrained** [comment]
> @pupbrained , it doesn’t quite work that way. You need to use std::optional:
> 
> https://github.com/getml/reflect-cpp/blob/main/docs/optional_fields.md
> 
> Then, you can retrieve the values using something like config.general.value_or(General())

I see, I was mostly trying to avoid optionals (to avoid needing multiple value_or's) but if that's necessary that's fine. Thanks for the quick response.

**Comment by liuzicheng1987** [comment]
@pupbrained , you can always abstract away the value_or's by using getters:

General get_general() const { return general.value_or(General()); }

I will think about this issue, but you would have to figure out whether a field has a default value at compile time. That's fairly tricky.

**Comment by ZXShady** [comment]
> @pupbrained , you can always abstract away the value_or's by using getters:
> 
> General get_general() const { return general.value_or(General()); }
> 
> I will think about this issue, but you would have to figure out whether a field has a default value at compile time. That's fairly tricky.

it would be possible to supply the defsult value as a templated function

```cpp
rfl::Defaulted<std:: string,[](){ return "Default";}> data;
```
