### ISSUE TITLE
Proposal: rfl:UnderlyingEnum

### ISSUE THREAD

**Issue by AnsiV01** [getml/reflect-cpp#130]
Hello everyone

I come with a proposal for a new class **rfl:UnderlyingEnum**. Based on the example in the enum section of the documentation, what would be the application of this:

**Without using rfl:UnderlyingEnum:**

```cpp
enum class Color { red, green, blue, yellow };

struct Circle {
  float radius;
  Color color;
};

const auto circle = Circle{.radius = 2.0, .color = Color::green};

rfl::json::write(circle);
```

This results in the following JSON string:

```json
{"radius":2.0,"color":"green"}
```

**With rfl:UnderlyingEnum:** 
```cpp
enum class Color { red, green, blue, yellow };

struct Circle {
  float radius;
  rfl:UnderlyingEnum<Color> color;
};

const auto circle = Circle{.radius = 2.0, .color = Color::green};

rfl::json::write(circle);
```

This results in the following JSON string:

```json
{"radius":2.0,"color":1}
```

I think this would be useful when the names of the enum values are very long and we want to keep the data size as small as possible, e.g. sending large amounts of data over a TCP socket, plus we want to keep the original fields in our struct

**Comment by liuzicheng1987** [comment]
Good idea.

I would design it as a processor, though.

So the syntax would be like:

rfl::json::write<rfl::UnderlyingEnum>(circle);

**Comment by liuzicheng1987** [comment]
@AnsiV01 , I have merged your PR. Thank you so much for your contribution. Really great work.

I think we can close this issue.
