### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by madmongo1** [getml/reflect-cpp#15]
Given this program:

```
#include <iostream>
#include <rfl.hpp>
#include <rfl/json.hpp>

struct foo
{
    std::string a;
    int         b;
};

int
main(int argc, char *argv[])
{
    auto x = foo { .a = "Hello, World!", .b = 100 };
    std::cout << rfl::json::write(x) << '\n';
}
```

How do I fix this error?
```
[build] /usr/bin/ld: CMakeFiles/scratch3.dir/scratch3/main.cpp.o: in function `auto rfl::internal::get_field_names<iron::foo>()':
[build] .../_deps/reflect-cpp-src/include/rfl/internal/get_field_names.hpp:126: undefined reference to `rfl::internal::fake_object<iron::foo>'
[build] collect2: error: ld returned 1 exit status
```

The program is linked with target `reflectcpp_static`.

Thank you.

**Comment by liuzicheng1987** [comment]
@madmongo1 , thanks to the input of @ecatmur, I was able to reproduce the issue and implement a fix (https://github.com/getml/reflect-cpp/commit/2e3872c651dc5c0a2c06fa4f0b094617c74fc8bd).

Can you confirm that this fixes your issue?

If no, can you provide the compiler used (including the version number) and the compiler flags used?
