### ISSUE TITLE
Bug: build system assumes compiler has or is GNU-like front-end

### ISSUE THREAD

**Issue by ethindp** [getml/reflect-cpp#153]
The CMake setup as it is right now assumes that the compiler in use is GCC, Clang, or some other compiler that has a GNU-like front-end. This is  obviously not always the case. I noticed this when trying to build the library with MSVC and it tried passing option `/Wextra` which doesn't exist.

**Comment by liuzicheng1987** [comment]
@ethindp , could you provide some context on what you were doing there?

We have Github Actions Workflows on MSVC and they run through just fine:

https://github.com/getml/reflect-cpp/actions/workflows/windows-msvc.yaml

Moreover, I know that people are using this on MSVC. So I would be very curious to find out what you where doing there.

**Comment by ethindp** [comment]
@liuzicheng1987 I'm not skilled enough for eliminating the structured binding requirement, sadly. I'm just wondering if we can eliminate the macro. We could then possibly make it so that the compiler could figure out the structure for us so there would be (theoretically) no upper limit at all to how many items could be in a struct, other than template depth restrictions, which is solvable (for the most part (well, Idk about MSVC but...)). Right now we're invoking a macro to generate this stuff... I suppose in the short term we could use something similar to that Python code that was in the comment to just generate the macro code directly without a macro, which in theory should solve our problem as a temporary workaround. Then we just limit it to like 2048 or 4096 or something. Maybe soome other metaprogramming library could help us here but I don't know one off the top of my head.

**Comment by ethindp** [comment]
@liuzicheng1987 I just included the library via CPM.cmake and then linked to `reflectcpp`. When I did so, MSVC complained about the `/Wextra` argument.

**Comment by liuzicheng1987** [comment]
@ethindp , could you make sure that this fixes the issue?
