### ISSUE TITLE
Link error with -fsanitize=undefined

### ISSUE THREAD

**Issue by ecatmur** [getml/reflect-cpp#16]
The following program fails to link on g++ 13.2.0 x86-64 Linux (Ubuntu):
```c++
#include <rfl/internal/get_field_names.hpp>
struct A { int i; };
int main() { rfl::internal::get_field_names<A>(); }
```
error: 
```
/tmp/ccKMlHON.o:a.cpp:function auto get_field_names<A>():(.text._Z15get_field_namesI1AEDav+0x5): error: undefined reference to 'fake_object<A>'
collect2: error: ld returned 1 exit status
```
might be related to #15 
reduced: https://godbolt.org/z/1jecWY947

possible workaround is to use `[[gnu::no_sanitize_undefined]]`

**Comment by liuzicheng1987** [comment]
@ecatmur , I was able to reproduce the issue and I can confirm that your proposed solution fixes it.

Here is what I have done: 

- I have implemented the fix you suggested.
- I have added -fsanitize=undefined as a flag to the CMakeList.txt of our tests, making it a permanent part of the testing pipeline.

Sorry I didn't merge your PR, but it would very likely have created merge conflicts with the f/msvc branch that I had opened in parallel (and that is now merged as well).

That being said, thank you very much for your issue and your contribution. This is exactly what open source should be all about.
