### ISSUE TITLE
Number systems support

### ISSUE THREAD

**Issue by RampantDespair** [getml/reflect-cpp#164]
Hey there,

Is currently possible to store numbers as different formats?
In my case, I was thinking about HEX which would be very useful for colors, mac addresses, etc.

But I suppose binary and octal could be useful for use cases other than mine.

**Comment by liuzicheng1987** [comment]
@RampantDespair , sounds like a good idea. Would you encode them as a string?

Here is how I think this could work:

```cpp
struct MyExampleStruct {
     rfl::Hex<int> hex;
};

const auto my_example = MyExampleStruct{.hex=30};

rfl::json::write(my_example);
```

```json
{"hex":"1E"}
```

What are your thoughts?

**Comment by RampantDespair** [comment]
@liuzicheng1987 
Yeah that would be great, something like
```cpp
rfl::Bin<int> bin = 64;
rfl::Oct<int> oct = 64;
rfl::Hex<int> hex = 64;
```
```json
{
  "bin": "0100 0000",
  "oct": "100",
  "hex": "40",
}
```
_No need for formatting on the bin value, just did it for clear representation_
And yeah I think your best bet would be to convert them to strings, because I know JSON5 [supports](https://json5.org/) it but I don't know if you use, nor do I think that binary and octal are supported at all.

**Comment by liuzicheng1987** [comment]
Done
