### ISSUE TITLE
undefined reference to `rfl::Generic::~Generic()'

### ISSUE THREAD

**Issue by Luffbee** [getml/reflect-cpp#176]
version v0.14.0

I see `Generic::~Generic() = default` in .cpp file. Is it the problem?

**Comment by Luffbee** [comment]
compiler: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by liuzicheng1987** [comment]
Yes, you need to link to the library or include the cpp file in your own project.

**Comment by Luffbee** [comment]
I have already link to the library. The 'undefined reference' error is reported by the linker. 

I think the problem is that you should NOT put the explicit-default destructer in the .cpp file.
As it seems like symbol of this destructer is not included in the library if it is not used in this library itself.

**Comment by Luffbee** [comment]
I'm sorry about this issue.
The problem is a mistake in my compilation script. It still uses this library as a header-only library, therefore, failed to link to the .a file.

**Comment by liuzicheng1987** [comment]
No problem 🤗
