### ISSUE TITLE
How to specify a parser for a field?

### ISSUE THREAD

**Issue by zhmt** [getml/reflect-cpp#188]
I have a json string that describes a  object. 
```
{ "Name": "Mike", Friends:"['John', 'Alice']"  }
```

Friends is a json string . 
I want convert it to a struct like this:
```
struct Person {
  std::string Name;
  std::vector<std::string> Friends; //  json string should be converted to vector<string>
}
```

Is it possible to specify a custome parser for field  "Friends"?

**Comment by liuzicheng1987** [comment]
Do you just need to read this weirdly formatted JSON or do you also want to write it?

There is no such thing as a custom parser for fields. I think you probably have to take a two-step approach.

**Comment by zhmt** [comment]
> Do you just need to read this weirdly formatted JSON or do you also want to write it?
> 
> There is no such thing as a custom parser for fields. I think you probably have to take a two-step approach.

Json string is filled in excel by hand.  This field is treated as string when excel is exported to csv,.
I have write a python script converting these fields to normal json objects.

Thanks for your reply.
