### ISSUE TITLE
Question: How to use rfl::Box and rfl::Ref within array structures/containers?

### ISSUE THREAD

**Issue by Lazrius** [getml/reflect-cpp#191]
Good afternoon. I have been studying the documentation of rfl::Box & rfl::Ref and I do not understand how to use them within array structures (or if that is even possible) and was wondering if it would be possible to have an explanation. For clarity, here is my use case:

Here is minimum code for reproducing:

```cpp
struct Ship
{
    std::wstring name;
}

struct Formation
{
    std::wstring formationName;
    std::unordered_set<rfl::Ref<Ship>> ships;
}

void Parse()
{
  std::string jsonStr = "[\"formationName\": \"Delta\", \"ships\": [{\"name\": \"Ship A\" }]}]";
  auto result = rfl::json::read<std::unordered_set<rfl::Ref<Formation>>>(jsonStr);
}
```

I would intend to pass around the rfl::Ref for other things to consume, and I want to avoid using raw pointers which makes using just a plain struct illogical.

What is the intended way to handle this kind of situation?
​
​
​
​
​
​
<details> 
  <summary>Full compiler error on MSVC for the curious (i cannot get Github to format this nicely):</summary>

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const _Ty' (or there is no acceptable conversion) [K:\GitHub\FLHook\build\plugins\spawner\Spawner.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54): error C2678:         with [K:\GitHub\FLHook\build\plugins\spawner\Spawner.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54): error C2678:         [ [K:\GitHub\FLHook\build\plugins\spawner\Spawner.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54): error C2678:             _Ty=rfl::Ref<Formation> [K:\GitHub\FLHook\build\plugins\spawner\Spawner.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54): error C2678:         ] [K:\GitHub\FLHook\build\plugins\spawner\Spawner.vcxproj]
  (compiling source file '../../../plugins/spawner/Spawner.cpp')
      C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\guiddef.h(192,15):
      could be 'bool operator ==(const GUID &,const GUID &)' [found using argument-dependent lookup]
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
          'bool operator ==(const GUID &,const GUID &)': cannot convert argument 1 from 'const _Ty' to 'const GUID &'
          with
          [
              _Ty=rfl::Ref<Formation>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
              Reason: cannot convert from 'const _Ty' to 'const GUID'
          with
          [
              _Ty=rfl::Ref<Formation>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
              No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
      C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\guiddef.h(192,15):
      or 'bool operator ==(const GUID &,const GUID &)' [synthesized expression 'y == x']
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
          'bool operator ==(const GUID &,const GUID &)': cannot convert argument 1 from 'const _Ty' to 'const GUID &'
          with
          [
              _Ty=rfl::Ref<Formation>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,63):
              Reason: cannot convert from 'const _Ty' to 'const GUID'
          with
          [
              _Ty=rfl::Ref<Formation>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,63):
              No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\utility(483,27):
      or       'bool std::operator ==(const std::pair<_Ty1,_Ty2> &,const std::pair<_Uty1,_Uty2> &)'
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
          'bool std::operator ==(const std::pair<_Ty1,_Ty2> &,const std::pair<_Uty1,_Uty2> &)': could not deduce template argument for 'const std::pair<_Ty1,_Ty2> &' from 'const _Ty'
          with
          [
              _Ty=rfl::Ref<Formation>
          ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
      while trying to match the argument list '(const _Ty, const _Ty)'
          with
          [
              _Ty=rfl::Ref<Formation>
          ]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xutility(531,54):
      the template instantiation context (the oldest one first) is
          K:\GitHub\FLHook\plugins\spawner\Spawner.cpp(101,30):
          see reference to class template instantiation 'rfl::Result<std::unordered_set<rfl::Ref<Formation>,std::hash<rfl::Ref<Formation>>,std::equal_to<rfl::Ref<Formation>>,std::allocator<rfl::Ref<Formation>>>>' being compiled
          K:\GitHub\FLHook\vendor\reflect-cpp\include\rfl\Result.hpp(39,40):
          see reference to class template instantiation 'std::unordered_set<rfl::Ref<Formation>,std::hash<rfl::Ref<Formation>>,std::equal_to<rfl::Ref<Formation>>,std::allocator<rfl::Ref<Formation>>>' being compiled
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\unordered_set(59,30):
          see reference to class template instantiation 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>' being compiled
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Alloc=std::allocator<rfl::Ref<Formation>>
          ]
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xhash(1675,10):
          while compiling class template member function 'void std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Forced_rehash(unsigned int)'
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Alloc=std::allocator<rfl::Ref<Formation>>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xhash(1628,23):
              see the first reference to 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Forced_rehash' in 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Rehash_for_1'
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Alloc=std::allocator<rfl::Ref<Formation>>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xhash(612,30):
              see the first reference to 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Rehash_for_1' in 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace'
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Alloc=std::allocator<rfl::Ref<Formation>>
          ]
              C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xhash(935,9):
              see the first reference to 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace' in 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::insert'
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Alloc=std::allocator<rfl::Ref<Formation>>
          ]
              K:\GitHub\FLHook\vendor\reflect-cpp\include\rfl\parsing\VectorReader.hpp(35,21):
              see the first reference to 'std::_Hash<std::_Uset_traits<_Kty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::insert' in 'rfl::parsing::VectorReader<R,W,VecType,ProcessorsType>::read::<lambda_2>::operator ()'
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Alloc=std::allocator<rfl::Ref<Formation>>
          ]
          and
          [
              R=rfl::json::Reader,
              W=rfl::json::Writer,
              VecType=std::unordered_set<rfl::Ref<Formation>,std::hash<rfl::Ref<Formation>>,std::equal_to<rfl::Ref<Formation>>,std::allocator<rfl::Ref<Formation>>>,
              ProcessorsType=rfl::Processors<>
          ]
              K:\GitHub\FLHook\vendor\reflect-cpp\include\rfl\Result.hpp(242,7):
              see the first reference to 'rfl::parsing::VectorReader<R,W,VecType,ProcessorsType>::read::<lambda_2>::operator ()' in 'rfl::Result<rfl::Ref<Formation>>::transform'
          with
          [
              R=rfl::json::Reader,
              W=rfl::json::Writer,
              VecType=std::unordered_set<rfl::Ref<Formation>,std::hash<rfl::Ref<Formation>>,std::equal_to<rfl::Ref<Formation>>,std::allocator<rfl::Ref<Formation>>>,
              ProcessorsType=rfl::Processors<>
          ]
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xhash(1724,18):
          while compiling class template member function 'bool std::_Uhash_compare<_Kty,_Hasher,_Keyeq>::operator ()<_Kty,_Kty>(const _Keyty1 &,const _Keyty2 &) noexcept(<expr>) const'
          with
          [
              _Kty=rfl::Ref<Formation>,
              _Hasher=std::hash<rfl::Ref<Formation>>,
              _Keyeq=std::equal_to<rfl::Ref<Formation>>,
              _Keyty1=rfl::Ref<Formation>,
              _Keyty2=rfl::Ref<Formation>
          ]
          C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xhash(150,18):
          see reference to variable template 'const bool _Nothrow_compare<std::equal_to<rfl::Ref<Formation> >,rfl::Ref<Formation>,rfl::Ref<Formation> >' being compiled
</details>

**Comment by AnsiV01** [comment]
The problem in your case is that you are trying to use `rfl::Ref<Formation>` as a key for `std::unordered_set`. You can find more on this topic here:

https://www.geeksforgeeks.org/how-to-create-an-unordered_set-of-user-defined-class-or-struct-in-c/

The easiest way would be to use `std::vector<rfl::Ref<Formation>>` instead of `std::unordered_set<rfl::Ref<Formation>>` in the `read` function and in the `Formation` struct: `std::vector<rfl::Ref<Ship>>` instead of `std::unordered_set<rfl::Ref<Ship>>`. 

Something like this:
```cpp
struct Ship
{
	std::wstring name;
};

struct Formation
{
	std::wstring formationName;
	std::vector<rfl::Ref<Ship>> ships;
};

...

std::string jsonStr = "[{\"formationName\": \"Delta\", \"ships\": [{\"name\": \"Ship A\" }]}]";
auto result = rfl::json::read<std::vector<rfl::Ref<Formation>>>(jsonStr);

```

**Comment by Lazrius** [comment]
I genuinely thought I had tried that but clearly I had not. That works as intended. thank you kindly.
