### ISSUE TITLE
Is it possible that this library is not limited to serialization and deserialization? If I implement a custom parser, can I dynamically call methods, access, and modify properties, etc.?

### ISSUE THREAD

**Issue by Candlend** [getml/reflect-cpp#201]

**Comment by liuzicheng1987** [comment]
Hi,

what exactly do you mean by dynamically accessing properties? Could provide a specific code example of something you would like to be able to do? 

Also, have you taken a look at rfl::to_view(...)? Do you think this might address some of the things you would like to do?

**Comment by Candlend** [comment]
Thank you for your previous response! While rfl::to_view(...) helps, it's not flexible enough for my needs.
I'm currently serializing my data into an rfl::Generic::Object using:
`rfl::Generic::Object obj = rfl::json::read<rfl::Generic::Object>(rfl::json::write(data));`
This allows me to use ImGui to automatically generate an Inspector interface for editing properties.
Is it possible to directly convert to rfl::Generic::Object instead of going through the write and read process?

**Comment by liuzicheng1987** [comment]
Sure, directly converting to Generic::Object should be possible.

**Comment by liuzicheng1987** [comment]
@Candlend , I have implemented generic reflection using rfl::to_generic and rfl::from_generic. It is in this feature branch:

https://github.com/getml/reflect-cpp/tree/f/generic_reflection

Dokumentation is here:

https://github.com/getml/reflect-cpp/blob/f/generic_reflection/docs/generic.md

Happy to hear your thoughts!

**Comment by Candlend** [comment]
Thanks for the quick update! It’s awesome. I'll try it out soon!
