### ISSUE TITLE
Is it possible to serilaize strcut to std::map<std::string,std::any>?

### ISSUE THREAD

**Issue by agrionoptera** [getml/reflect-cpp#222]
struct Person {
  std::string first_name;
  std::string last_name;
  int age;
};
how to serialize strcut to std::map<std::string,std::any>
map key is member name and map value is member value

**Comment by liuzicheng1987** [comment]
@agrionoptera , the problem at the moment is that we don't support std::any. 

You try to use rfl::Generic instead, maybe that covers your use case.

If not, please let me know at greater detail what it is that you are trying to do and I will think of a way to help you.
