### ISSUE TITLE
Wrong filename in logic checking for local `ctre.hpp`

### ISSUE THREAD

**Issue by Harry-Chen** [getml/reflect-cpp#224]
Should check for `ctre.hpp`, not `ctre.h` in:

https://github.com/getml/reflect-cpp/blob/b3b0370ce2737336d0482cf6a23d4eb7daf75a3e/include/rfl/PatternValidator.hpp#L6-L10

**Comment by liuzicheng1987** [comment]
Great catch. Feel free to open a PR, otherwise I will fix it tonight.
