### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by BestITUserEUW** [getml/reflect-cpp#227]
Hey is it possible that you make a new release. I would like to pull in the changes since v0.14.1

**Comment by liuzicheng1987** [comment]
OK, will do so soon.

**Comment by liuzicheng1987** [comment]
Hi @BestITUserEUW , 

I still want to get this PR over the finish line, because I promised I would:

https://github.com/getml/reflect-cpp/pull/234

Then I will do the release.

**Comment by liuzicheng1987** [comment]
@BestITUserEUW 

https://github.com/getml/reflect-cpp/releases/tag/v0.15.0

Done
