### ISSUE TITLE
std::variant serialization of empty types can be irreversible

### ISSUE THREAD

**Issue by 17steen** [getml/reflect-cpp#230]
the variant's current alternative type is not serialized, making it impossible to recover when deserializing
Making this sort of use case where tagged unions are sometimes left empty unusable.

There are however no compile errors, so i believe this should either be supported or throw a compiler error.

```cpp
    struct button_pressed_t
    {
        bool operator==(const button_pressed_t&) const = default;
    };

    struct button_released_t
    {
        bool operator==(const button_released_t&) const = default;
    };

    struct key_pressed_t
    {
        char key;

        bool operator==(const key_pressed_t&) const = default;
    };

    using my_event_type_t = std::variant<button_pressed_t, button_released_t, key_pressed_t>;
    struct my_event_t
    {
        my_event_type_t event;

        [[nodiscard]] constexpr bool operator==(const my_event_t& other) const noexcept = default;
    };

    auto my_event = my_event_t{.event = key_pressed_t{}};

    auto as_json = rfl::json::write(my_event, rfl::json::pretty);
    auto reparsed_event = rfl::json::read<my_event_t>(as_json).value();

    // Should be equal
    ASSERT_NE(my_event, reparsed_event);
```

**Comment by liuzicheng1987** [comment]
Hi @17steen , 

how would you suggest we support this? If the struct is empty, there is nothing to serialize.

This is exactly the kind of use case we have rfl::TaggedUnions for. Have you taken a look at that?

https://github.com/getml/reflect-cpp/blob/main/docs/variants_and_tagged_unions.md

You would only have to change one line of your code:

```cpp
using my_event_type_t = rfl::TaggedUnion<"event",button_pressed_t, button_released_t, key_pressed_t>;
```

**Comment by 17steen** [comment]
Hello @liuzicheng1987 

The variant is aware of which alternative it currently holds, this could be serialized too, either its index or a type id?
But indeed the tagged union is an alternative that works.

I am pointing out that I as a user could use a variant type, in a sound way, and have serialization not work, while it is documented as supported, which i believe is a bug.
I believe these cases where the variant's alternative is empty should either be supported, or fail to compile.

(love the work of the library, I don't mean to come off as rude or anything)

**Comment by liuzicheng1987** [comment]
@17steen , totally fine, you are not coming off as rude.

I think the problem is not really about empty alternatives. For instance, this would be fine:

```cpp
    struct button_pressed_t{};
    struct button_released_t{char button;};
    struct key_pressed_t{char key;};
```

But this would not be:
```cpp
    struct button_pressed_t{char button;};
    struct button_released_t{char button;};
    struct key_pressed_t{char key;};
```

So we would have to check at compile time whether the named-tuple-representation for a class and all the classes it owns is identical, which would certainly introduce a lot of compile overhead, and, in some recursive cases, would be impossible.

**Comment by liuzicheng1987** [comment]
@17steen , sorry, I missed your suggestion about the index...yeah, I guess serializing the index or type id might actually be possible, even though it would pretty much be the same as what we already have with rfl::TaggedUnion. Let me think about that.

**Comment by 17steen** [comment]
The main advantage would be that people would not have to migrate from std::variant and use third party data structures in their types, other than that it's indeed pretty much the same as the TaggedUnion

**Comment by liuzicheng1987** [comment]
@17steen , this could be another processor...

**Comment by 17steen** [comment]
i guess it could be a processor but still i believe then that the default implementation would be broken 

because sound c++ standard code like the one you posted here:
> ```c++
>     struct button_pressed_t{char button;};
>     struct button_released_t{char button;};
>     struct key_pressed_t{char key;};
> ```
is silently broken, allowing it to compile is a bug

i don't think there is a way to know that this code doesn't work without debugging or knowing the intrinsics

**Comment by liuzicheng1987** [comment]
@17steen, here is the PR:

https://github.com/getml/reflect-cpp/pull/246

Happy to hear your thoughts!

**Comment by 17steen** [comment]
I think this looks great 👍
