### ISSUE TITLE
gcc segfault when optimized

### ISSUE THREAD

**Issue by BestITUserEUW** [getml/reflect-cpp#240]
Segmentation fault in rfl::json::read. Reproducible example:

```cpp
#include <string>
#include <rfl/json/read.hpp>

struct Data {
    std::string prop1;
    std::string prop2;
    std::string prop3;
    std::string prop4;
    std::string prop5;
    std::string prop6;
};

int main(void) {
    const std::string data{R"({"prop1": "", "prop2": "", "prop3": "", "prop4": "", "prop5": "", "prop6": ""})"};
    auto res = rfl::json::read<Data>(data);
    if (!res) {
        std::cout << res.error().value().what();
        return 1;
    }
    return 0;
}
```

Platform:         `Ubuntu 24.04 / x86_64 GNU/Linux ` and `Ubuntu 22.04 aarch64`
gcc version:     `gcc (Ubuntu 12.3.0-17ubuntu1) 12.3.0`
clang version:  `Ubuntu clang version 18.1.3 (1ubuntu1)`

Compile: 
```bash
g++ test.cpp -o test -O3 -ggdb -Wall -Wextra -lreflect-cpp
```

GDB Inspect:

`
gdb -> file test.cpp -> run -> bt 20
`

So this happened when trying to run release build which enables -O3. I broke it down to this example
and tried to track the error down with gdb and got the following stacktrace: [stacktrace](https://github.com/user-attachments/files/17573658/stacktrace.txt). It goes to include/rfl/json/parsing/ViewReader.hpp:33:

```cpp
::new (_t) Target(std::move(*_s));
```

I was unable to fully understand the parsing due to skill issues, so i went back in commits to find where this issue appeared as i was already using reflect-cpp v0.14.1 in production without issues.

This is the pr that added this problem: https://github.com/getml/reflect-cpp/pull/181. It seems like there is something wrong with std::launder i removed changes and retried till i found the source of the problem which is in rlf::Tuple::get implementation where you added std::launder. 

I didn't have more time working on this but this is a patch file i made which solves this problem.

[launder.patch](https://github.com/user-attachments/files/17573760/launder.patch) 

With this patch everything runs fine under x86 and aarch64. But i don't know if that is proper solution as i don't understand what this changes so i didn't do a pr on this.

This patch works on current main branch usage:
```bash
git apply launder.patch
```

Observations i made:

- if you remove prop6 segmentation fault is gone and everything works once struct is > 5 properties segfault happens. 
- gcc -O2 works.
- gcc only emits some warnings about unused variables when compiling with -Wall -Wextra. 
- compiling with clang -O3 works
- enabling any sanitizer removes the segfault. Maybe some optimizations get turned off ?
- adding data to the json string also doesn't change anything

**Comment by BestITUserEUW** [comment]
Could be related to:: https://github.com/getml/reflect-cpp/pull/226

**Comment by liuzicheng1987** [comment]
@BestITUserEUW , the issue should be fixed with yesterday's commit in main.

Could you checkout main and see whether the issue persists?

**Comment by liuzicheng1987** [comment]
@BestITUserEUW , thanks for the patch. I think it is extremely weird that std::launder should cause this problem, but it matches my own observations.

According to the documentation, we absolutely should have std::launder here, but the observed behavior is the opposite. Possibly a bug in GCC 12?

https://en.cppreference.com/w/cpp/utility/launder

**Comment by BestITUserEUW** [comment]
@liuzicheng1987 Just tried out latest commit from main, issue still persists. 

I also applied launder.patch still fixes it. 

Might be a gcc bug i just tried out:

- gcc-14 (Ubuntu 14.2.0-4ubuntu2~24.04) 14.2.0 
- gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0

Works on both of them with -O3.

**Comment by Harry-Chen** [comment]
It might be `std::launder` that reveals some hidden problem, e.g. triggers an UB. But I did not investigate deeply.

**Comment by liuzicheng1987** [comment]
@BestITUserEUW , you are right, I can reproduce the issue in the testing pipeline when I use the *exact same* compiler settings as you have provided. There are other examples where it occurs.

Here is what I can say for sure:

- Removing `std::launder` in `Tuple::get` reliably removes the issue.
- If @Harry-Chen is right and there is some underlying UB, that UB must be somewhere in rfl::Tuple. The issue occurs even in instances where don't even use `rfl::json::read` or where we use the `rfl::DefaultIfMissing` preprocessor (which works without the placement-new operator).

**Comment by liuzicheng1987** [comment]
@Harry-Chen and @BestITUserEUW , using `std::bit_cast` instead of `reinterpret_cast` seems to fix the issue. I like this solution, because it is clearly not UN, whereas simply removing `std::launder` would be UB, even if it works in practice.

**Comment by BestITUserEUW** [comment]
@liuzicheng1987 Sounds great.

**Comment by liuzicheng1987** [comment]
@BestITUserEUW , I just merged the PR into main...could you check again whether that resolves the issue? (I would be very surprised if it didn't, because I was able to reproduce and then fix it, but just want to make sure.)

**Comment by BestITUserEUW** [comment]
@liuzicheng1987 Works on my local computer. I'll give you an update once i tested with my project.

**Comment by liuzicheng1987** [comment]
@BestITUserEUW , thank you so much for flagging this and your helpful input on this issue!

**Comment by BestITUserEUW** [comment]
@liuzicheng1987 Works in my project on target hardware too. Thanks for resolving this so fast.
