### ISSUE TITLE
CMake complaining that cxx_std_20 is not supported by Clang 19.1.3

### ISSUE THREAD

**Issue by jowillianto** [getml/reflect-cpp#253]
Platform : MacOs Sequoia 15.1 Beta
Compiler : Clang 19.1.3
Cmake : 3.31.0
Ninja : 1.12.1

Reproduction Steps : 
- Run cmake to compile the project with any random file. 
- Fail with the following : 
<img width="761" alt="Screenshot 2024-11-12 at 1 48 35 PM" src="https://github.com/user-attachments/assets/bed2a50d-2072-41e5-b055-00a7f6c95da7">

Not really sure why this happens as cxx_std_20 check is considered part of cmake standard. However, setting CMAKE_CXX_STANDARD should be enough

**Comment by jowillianto** [comment]
I have commented the problematic line in the CMakeLists and would like to contribute
How do I start contributing ?

**Comment by Urfoex** [comment]
FYI: 
https://stackoverflow.com/a/70667652
https://www.reddit.com/r/cpp_questions/comments/v6g536/comment/ibfdh6i/

Setting things for targets should be preferred over polluting the global scope. Especially for a library, that is used by others.
