### ISSUE TITLE
How to enable the TOML format in Linux system

### ISSUE THREAD

**Issue by xiaoyaodid** [getml/reflect-cpp#255]
When I set REFLECTCPP_TOML option to ON. 
the CMake code below show :
```
if (MSVC)
        target_link_libraries(reflectcpp PRIVATE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/tomlplusplus${CMAKE_STATIC_LIBRARY_SUFFIX}")
else ()
        target_link_libraries(reflectcpp PRIVATE "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib/libtomlplusplus${CMAKE_STATIC_LIBRARY_SUFFIX}")
endif ()
```
But as you know, the [toml++](https://github.com/marzer/tomlplusplus) readme guidline said that :
🍦️ Single-header flavour
1. Drop [toml.hpp](https://raw.githubusercontent.com/marzer/tomlplusplus/master/toml.hpp) wherever you like in your source tree
2. There is no step two

So it can't install any library or header files into the installed dir.

So how can I use the TOML library in the right way?

**Comment by liuzicheng1987** [comment]
@xiaoyaodid , sorry, I just realized there was a line missing in the README. I fixed it. If you pull from `main` again, you should be able to compile with TOML support using the instructions I have given you above.

**Comment by xiaoyaodid** [comment]
OK, I build it successfully. Thank you very much!

**Comment by xiaoyaodid** [comment]
It solved
