### ISSUE TITLE
Parsing from `std::string_view`

### ISSUE THREAD

**Issue by GoldsteinE** [getml/reflect-cpp#269]
Currently e.g. `rfl::json` provides two ways to parse a string: from `std::string` or from `std::istream` (where the second delegates to the first). That means that parsing from `std::string_view` currently requires an allocation. `yyjson_read()` doesn’t take ownership of the passed string, so parsing directly from `std::string_view` should be possible unless I’m missing something.

I think the same holds for other formats, but I only checked yyjson and pugixml.

**Comment by liuzicheng1987** [comment]
@GoldsteinE , true, none of the formats support `std::string_view`. But it would be a good idea and should be fairly easy to implement.

**Comment by liuzicheng1987** [comment]
Resolved; https://github.com/getml/reflect-cpp/pull/312

**Comment by GoldsteinE** [comment]
Thanks!
