### ISSUE TITLE
rfl::yaml::read<uint8_t> is parsed as a character instead of a number

### ISSUE THREAD

**Issue by lhruby** [getml/reflect-cpp#270]
When parsing a `uint8_t` as a yaml using `rfl::yaml::write`, the value is correctly parsed as `dummy_uint8_t=48`. Note, 48 is the ASCII code for '0'.

Reading the value back using `rfl::yaml::read<uint8_t>` does however yield `dummy_uint8_t=0`, as 48 is now interpreted as a character instead of a number.

**Comment by liuzicheng1987** [comment]
Interesting, thanks for pointing it out. I will take a look.

**Comment by liuzicheng1987** [comment]
Yes, it has to do with the underlying library and we need to write a workaround. I think I will get to it over the next couple of days.

**Comment by lhruby** [comment]
Thanks, no rush.

**Comment by liuzicheng1987** [comment]
@lhruby , it was indeed how the underlying library handles these kind of types. Luckily, there is a very simple workaround.

Sorry it took me a while to get to this...I really wanted to get the Avro support over the finish line.

**Comment by lhruby** [comment]
Thanks @liuzicheng1987, your effort is very much appreciated.
