### ISSUE TITLE
Is it possible to reflect old C-style array field?

### ISSUE THREAD

**Issue by goldenbull** [getml/reflect-cpp#271]
If a struct contains a field like `char name[32]` , the code can not compile.

**Comment by liuzicheng1987** [comment]
@goldenbull, let me refer you to the documentation:

https://rfl.getml.com/c_arrays_and_inheritance/#c-arrays

Because inferring whether something is a C array, it is not supported by default, but you can pass a compile time flag to activate support for C arrays.
