### ISSUE TITLE
Howto == a TaggeUnion?

### ISSUE THREAD

**Issue by ttamttam** [getml/reflect-cpp#272]
Hello.

What would be the way to define `operator==`:
```cpp
bool operator==(MyType &lhs, MyType& rhs);
```
for this type:

```cpp
using MyType = rfl::TaggedUnion < "my_type",	Typ1, Typ2, Typ3>;
```
provided that Typ1, Typ2 and Typ3 have their own `operator==`?

All my tentatives failed until now :-(

Best regards

**Comment by ttamttam** [comment]
Replying to myself, here is the working code I eventually obtained:

```cpp
bool operator==(const MyType& lhs, const MyType& rhs)
{
	return lhs.variant().index() == rhs.variant().index() &&
                   rfl::visit([](const auto& l, const auto& r) { return l == r; }, lhs.variant(), rhs.variant());
}
```

Best regards

**Comment by liuzicheng1987** [comment]
You got it. Feel free to open a PR containing that code snippet.

**Comment by ttamttam** [comment]
Not sure where to put it?

**Comment by liuzicheng1987** [comment]
@ttamttam , just put it in TaggedUnion.hpp

**Comment by ttamttam** [comment]
OK. At first, I was not sure if your idea was to modify the doc. I made an attempt at moving my code into TaggedUnion.

Would certainly be needed for some other components (Description, etc).

Best regards
