### ISSUE TITLE
Redesign the Writer

### ISSUE THREAD

**Issue by liuzicheng1987** [getml/reflect-cpp#36]
The Reader and Writer have been designed with various JSON libraries in mind. Whereas the design for Reader seems fine, the Writer needs an update.

The problem is that many libraries for binary formats require you to directly assign children to their parents as opposed to first creating the children and then assigning them to their parents.

For instance, pugixml requires you to do this:

```cpp
auto node_child = node_parent.append_child(_key.c_str());
```

Likewise, libbson (https://mongoc.org/libbson/current/creating.html):

```cpp
bson_append_array_builder_begin (&parent, "foo", 3, &bab);
bson_array_builder_append_int32 (bab, 9);
bson_array_builder_append_int32 (bab, 8);
bson_array_builder_append_int32 (bab, 7);
bson_append_array_builder_end (&parent, bab);
```

The current workaround it to have structures like OutputArray and OutputObject (https://github.com/getml/reflect-cpp/blob/f/xml/include/rfl/flexbuf/OutputArray.hpp). This works well, but it adds an unnecessary extra layer and runtime overhead.

This could be avoided by a redesign of the writer that takes these limitations into account.

**Comment by jimixxperez** [comment]
I personally don't think the Writer and Reader interfaces (with associated Parser) don't provide the clearest and flexible approach - especially in comparison to Rust Serdes design.  Even though Rust native traits don't have a natural match in cpp we could strive a similar approach.
- create a well defined data model -> https://serde.rs/data-model.html
- design Serialize and Deserialize "Traits" that map from and into the data model. -> https://serde.rs/impl-serialize.html

**Comment by liuzicheng1987** [comment]
@jimixxperez, would that mean that the users of our library would have to inherit some base class from our library?
