### ISSUE TITLE
Is it possible to have the JSON string returned from rfl::json::write be 'pretty'?

### ISSUE THREAD

**Issue by Lazrius** [getml/reflect-cpp#62]
Hi again! Just wondering if it's possible to have the JSON config be transformed into a pretty string or at least one that is more human readable. I wanted to generate some default configuration files, but them being minified is a bit of a problem.

**Comment by liuzicheng1987** [comment]
We are using YYJSON under-the-hood. I haven’t bothered to figure out how to do that with YYJSON yet.

 I think if we add an extra parameter with a default value to rfl::json::write and rfl::json::save thet would fix the problem. rfl::xml::write already has such a parameter.

Again, a PR us more than welcome.

**Comment by liuzicheng1987** [comment]
Apparently YYJSON has a flag like this:

yyjson_write_flag flg = YYJSON_WRITE_PRETTY | YYJSON_WRITE_ESCAPE_UNICODE;
yyjson_write_err err;
yyjson_mut_write_file("/tmp/config.json", doc, flg, NULL, &err);

I think we could just add a Boolean variable called “pretty” to rfl::json::write, which is false by default.

**Comment by liuzicheng1987** [comment]
@Lazrius I have opened a feature branch:

https://github.com/getml/reflect-cpp/tree/f/pretty_json

Does that fix the issue in your mind?

**Comment by Lazrius** [comment]
Good afternoon. I will try and test the branch this evening or tomorrow if I have time, many thanks for your work!

**Comment by liuzicheng1987** [comment]
@Lazrius , I have made some minor changes. Here is the documentation on how to use it:

https://github.com/getml/reflect-cpp/blob/f/pretty_json/docs/json.md

**Comment by Lazrius** [comment]
Yep. tested that, it works flawlessly!

**Comment by liuzicheng1987** [comment]
Merged into main (tagged the wrong issue, though):

https://github.com/getml/reflect-cpp/commit/87cad2665427733f0147ed664dec6d00999882cf
