### ISSUE TITLE
How to handle modifying a structs properties

### ISSUE THREAD

**Issue by RudyB** [getml/reflect-cpp#75]
I'm very interested in using your tool. The main question I have is regarding deserialization of a structure with properties that have changed. 

For example, imagine version 1.0 of my software serializes a Data struct with an int32_t and a std::string. Version 2.0 adds a double to a data struct. How would I handle deserializing the older data struct in newer software?

**Comment by liuzicheng1987** [comment]
Two possible solutions:

1. You can make the additional fields optional

https://github.com/getml/reflect-cpp/blob/main/docs/optional_fields.md

2. You can use API versioning

https://github.com/getml/reflect-cpp/blob/main/docs/backwards_compatability.md
