### ISSUE TITLE
Separate yyjson and ctre?

### ISSUE THREAD

**Issue by hlewin** [getml/reflect-cpp#79]
Hello!

I was thinking about if it would be possible to separate reflect-cpp from yyjson, ie not to bundle yyjson per se but to do so only if requested by cmake options. The alternative would be to rely on vcpkg or to rely on a system-wide installation of yyjson.

This would have the following benefits:
- reflect-cpp could be used as pure reflection library
- yyjson would not have to be maintained (updated) internally
- For the case of a system-wide installation of yyjson and reflect-cpp there would be no file clashes

The same argument applies to the `ctre.hpp` shipped with reflect-cpp. This should also be separated for the same reasons.

Any thoughts on this?

**Comment by liuzicheng1987** [comment]
Yes, we have had this discussion before, here are my thoughts:

We want to give people an "out-of-the-box" experience. You download the library and you are ready to give it a try. 

I think many people will give a new open-source library 5-10 minutes. If they can't make it work by then, they give up. If they are forced to install YYJSON or CTRE on their own just to give the library a first try, that's going to be a problem.

JSON is by far the most widely used serialization format, so it makes sense to support JSON out-of-the-box.

If you aren't interested in YYJSON, then you can just use reflect-cpp as a header-only library.

**Comment by hlewin** [comment]
> We want to give people an "out-of-the-box" experience. You download the library and you are ready to give it a try.
> 
> I think many people will give a new open-source library 5-10 minutes. If they can't make it work by then, they give up. If they are forced to install YYJSON or CTRE on their own just to give the library a first try, that's going to be a problem.

I fully understand this and would preserve this as the default behaviour. My intention is to make things more suitable for specialized use-cases and system-wide installs where it is no problem to supply a few more additional cmake-arguments.

I'll sketch out what I am thinking of:/df
1. Move third-party dependency-headers to `include/rfl/third-part`. This is necessary to avoid headers already present in the system when doing a system-wide install and to avoid clashes between possible different versions of eg yyjson.h if there are different versions floating around.
2. Introduce a cmake-option `REFLECTCPP_USE_BUNDLED_DEPENDENCIES` that defaults to `ON` and makes the lib use (and install) the bundled dependencies.
3. Else, if `REFLECTCPP_USE_BUNDLED_DEPENDENCIES` is `OFF`, but `REFLECTCPP_USE_VCPKG` is `ON`, use vcpkg download the dependencies and use that version.
4. Else, if both  `REFLECTCPP_USE_BUNDLED_DEPENDENCIES` and `REFLECTCPP_USE_VCPKG` is `OFF`, rely on the user to supply the dependencies (in eg CMAKE_MODULE_PATH, CMAKE_PREFIX_PATH or the like). In this case reflectcpp would get installed as header-only library.

**Comment by hlewin** [comment]
I forgot to mention: I am not asking you to implement these things. This is something I would do next time I have some time at my hand. Am just trying to get your opinion on this to reduce the risk of wasting time and work.

**Comment by liuzicheng1987** [comment]
Sounds like a great solution, if you submit a PR along the lines you have described, I will accept.
