### ISSUE TITLE
Error when struct has a base class

### ISSUE THREAD

**Issue by lixin-wei** [getml/reflect-cpp#82]
The following code will fail to compile:

```cpp
struct EmptyBase {};
struct DerivedStruct : public EmptyBase {
  int x;
};

DerivedStruct derived;
rfl::to_view(derived);
```

Because the auto generated default constructor of `DerivedStruct` is `DerivedStruct(EmptyBase, int)`. Which has 2 params.

So `has_n_fields<DerivedStruct, 2>` will hold, then `auto &[f1, f2] = derived` will fail.

I've searched around and just find a non-standard gcc traits called [direct_base](https://gcc.gnu.org/onlinedocs/gcc-4.7.2/libstdc++/api/a00909.html) which might help.

Do you guys have any better idea?

**Comment by schaumb** [comment]
I have a compiler-independent solution for that.

When the detection happens (CountFieldHelper), it should be a specific ubiq type, which can be convertible to only the class's base class. 
https://github.com/vizzuhq/vizzu-lib/blob/main/src/base/refl/auto_struct.h#L29
With this ubiq, when the wrong field count is first calculated, it should be checked that the aggregated initialization first K "member" can be a parent class of the original. https://github.com/vizzuhq/vizzu-lib/blob/main/src/base/refl/auto_struct.h#L60-L64

General implementation does not exist yet as far as I know. 
https://github.com/boostorg/pfr/issues/56#issuecomment-1824106120


Special cases
---

There are some special classes where it doesn't work when the parent class is a member too.

like the following:

```cpp
struct Base {};

struct Derived: Base {
  Base as_member_too; // recognized as base class
};
```

A method should exist that can filter these unconventional cases with some compilation time structures, like a compile time set that tracks the already recognized base classes.

--- 

Other special case when the grandparent is the member:

```cpp
struct BaseBase{};
struct Base: BaseBase{};

struct Derived: Base {
  BaseBase memb; 
};
```

This can be eliminated with a recursive base-ubiq recognizer and a compile time set. But with the technique, this class is the same, which makes the solution unambiguous.
```cpp
struct BaseBase{};
struct Base: BaseBase{};

struct Derived: Base, BaseBase {};
```

**Comment by liuzicheng1987** [comment]
@schaumb , I will take a closer look at your solution and add it to the library.

**Comment by lixin-wei** [comment]
@liuzicheng1987 Do you start coding? If not I'm willing to have a try.

**Comment by liuzicheng1987** [comment]
@lixin-wei , no, I haven't. Go for it.

**Comment by Candlend** [comment]
I encountered a compilation error when attempting to serialize a derived struct using the rfl::json::write function in the following code snippet:

```
struct Base
{
};

struct Derived : Base
{
    int x;
};

int main(int /*argc*/, char ** /*argv*/)
{
    auto d = Derived();
    std::cout << rfl::json::write(d) << std::endl;
    return 0;
}
```
